// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwDADiwZmaVizlq-wAWXKw-xIVjzbzF2E',
    appId: '1:820214305360:web:13c6bd0f0d6b95858e7755',
    messagingSenderId: '820214305360',
    projectId: 'childmobile-ee6f3',
    authDomain: 'childmobile-ee6f3.firebaseapp.com',
    storageBucket: 'childmobile-ee6f3.firebasestorage.app',
    measurementId: 'G-K2VMZ06SCF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBPXfTPHdTLH00Af87lbk9RD4FeOXKTFQ',
    appId: '1:820214305360:android:5013fc7f9419679f8e7755',
    messagingSenderId: '820214305360',
    projectId: 'childmobile-ee6f3',
    storageBucket: 'childmobile-ee6f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBp8esjjW05P1VDPav5rRR62v0JO3qogjw',
    appId: '1:820214305360:ios:63950c5e76df51b68e7755',
    messagingSenderId: '820214305360',
    projectId: 'childmobile-ee6f3',
    storageBucket: 'childmobile-ee6f3.firebasestorage.app',
    iosBundleId: 'com.example.childMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBp8esjjW05P1VDPav5rRR62v0JO3qogjw',
    appId: '1:820214305360:ios:63950c5e76df51b68e7755',
    messagingSenderId: '820214305360',
    projectId: 'childmobile-ee6f3',
    storageBucket: 'childmobile-ee6f3.firebasestorage.app',
    iosBundleId: 'com.example.childMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwDADiwZmaVizlq-wAWXKw-xIVjzbzF2E',
    appId: '1:820214305360:web:1cb0d0275634e2c98e7755',
    messagingSenderId: '820214305360',
    projectId: 'childmobile-ee6f3',
    authDomain: 'childmobile-ee6f3.firebaseapp.com',
    storageBucket: 'childmobile-ee6f3.firebasestorage.app',
    measurementId: 'G-702P31RX86',
  );
}
